name: 'GHCR Login'
version: 1
description: Log in to GitHub Container Registry using secrets from secret-server.

runs:
  using: composite
  steps:
    - uses: wow-look-at-my/actions@secret-server#latest

    - name: Login to GHCR
      shell: bash
      run: echo "$GHCR_WRITE_TOKEN" | docker login ghcr.io -u x-access-token --password-stdin
